version: "3.7"

services:
 notebook:
  build:
   dockerfile: octave.Dockerfile
   context: .
  command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
  volumes:
   - ./exchange:/exchange
  ports:
   - 8888:8888
